import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonButtons, IonSpinner, IonLoading } from '@ionic/react';
import React, { useEffect, useState } from 'react';
import './Home.css';
import { NavButtons } from '../components/NavButtons';


import { LRITableHeaders } from '../components/LRITableHeaders';
import { TableWrapper } from '../components/TableWrapper';

import { LRItableCollectionBody } from '../components/LRItableCollectionBody';


const dash = [
  {
      "router_customer_brand_id": "82",
      "companyName": null,
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "100",
      "companyName": null,
      "logo": null,
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "223",
      "companyName": null,
      "logo": null,
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "257",
      "companyName": null,
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "40",
      "companyName": null,
      "logo": null,
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "51",
      "companyName": null,
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "54",
      "companyName": null,
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "126",
      "companyName": "2 Point 0",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "53",
      "companyName": "3dslim",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "2",
      "companyName": "Action wear",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "117",
      "companyName": "ALMA SHOP",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "249",
      "companyName": "Amazon",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "58",
      "companyName": "Anata Technolgy",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "123",
      "companyName": "Any d'Avray My Energy",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "188",
      "companyName": "Aquabion",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "3",
      "idprint": "4",
      "nbblocked": "2",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "3"
  },
  {
      "router_customer_brand_id": "118",
      "companyName": "AQUILUX",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "163",
      "companyName": "Atelier des plantes",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "240",
      "companyName": "Atelier Fanny",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "110",
      "companyName": "AZ VITAMINS",
      "logo": null,
      "nbnew": "41",
      "idnew": "1",
      "nbprint": "14",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "14"
  },
  {
      "router_customer_brand_id": "227",
      "companyName": "Babyrun",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "75",
      "companyName": "Bbcpro",
      "logo": null,
      "nbnew": "2",
      "idnew": "1",
      "nbprint": "20",
      "idprint": "4",
      "nbblocked": "53",
      "idblocked": "3",
      "nbout_of_stock": "3",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "20"
  },
  {
      "router_customer_brand_id": "64",
      "companyName": "Biform",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "67",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "67"
  },
  {
      "router_customer_brand_id": "209",
      "companyName": "Biofar",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "276",
      "companyName": "Bionarel",
      "logo": "",
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "20",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "20"
  },
  {
      "router_customer_brand_id": "164",
      "companyName": "Biophenix",
      "logo": "",
      "nbnew": "2",
      "idnew": "1",
      "nbprint": "16",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "9",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "16"
  },
  {
      "router_customer_brand_id": "86",
      "companyName": "Biovea",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "258",
      "companyName": "Bistrot CBD",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "3",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "31",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "3"
  },
  {
      "router_customer_brand_id": "159",
      "companyName": "Bonito",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "56",
      "companyName": "Boto",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "41",
      "companyName": "C1",
      "logo": "",
      "nbnew": "124",
      "idnew": "1",
      "nbprint": "98",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "98"
  },
  {
      "router_customer_brand_id": "171",
      "companyName": "Caluli Company GmbH",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "219",
      "companyName": "Cannaflora",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "42",
      "companyName": "CBDHEMCO",
      "logo": "",
      "nbnew": "2",
      "idnew": "1",
      "nbprint": "6",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "6"
  },
  {
      "router_customer_brand_id": "101",
      "companyName": "CELERGEN",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "2",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "2"
  },
  {
      "router_customer_brand_id": "182",
      "companyName": "Cellaire",
      "logo": "logo_cellaire.png",
      "nbnew": "2",
      "idnew": "1",
      "nbprint": "54",
      "idprint": "4",
      "nbblocked": "2",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "54"
  },
  {
      "router_customer_brand_id": "277",
      "companyName": "Cosmic Goddess",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "270",
      "companyName": "Cruel Pancake",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "3",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "165",
      "companyName": "Cryoligne",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "272",
      "companyName": "Dasteli",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "229",
      "companyName": "DermaTattoo",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "4",
      "idprint": "4",
      "nbblocked": "19",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "4"
  },
  {
      "router_customer_brand_id": "273",
      "companyName": "DHLighting",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "4",
      "idprint": "4",
      "nbblocked": "44",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "4"
  },
  {
      "router_customer_brand_id": "247",
      "companyName": "Dose Mindcare",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "7",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "7"
  },
  {
      "router_customer_brand_id": "62",
      "companyName": "Effiplex",
      "logo": null,
      "nbnew": "4",
      "idnew": "1",
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "173",
      "companyName": "Electronic Capacity",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "202",
      "companyName": "Elite Pharam SA",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "55",
      "companyName": "Endurancer",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "153",
      "companyName": "Eric Favre Omnibiz",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "394",
      "idprint": "4",
      "nbblocked": "3",
      "idblocked": "3",
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "394"
  },
  {
      "router_customer_brand_id": "211",
      "companyName": "Expro Global Ltd",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "44",
      "companyName": "Fiddiam allemand",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "48",
      "companyName": "Fiddiam pays de l'est",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "46",
      "companyName": "Fiddiam XD",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "150",
      "companyName": "FIZZZ",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "224",
      "companyName": "Formidable service",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "225",
      "companyName": "Freskincare",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "28",
      "idprint": "4",
      "nbblocked": "2",
      "idblocked": "3",
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "28"
  },
  {
      "router_customer_brand_id": "176",
      "companyName": "Gigafit",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "133",
      "companyName": "Go Online Services INC.",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "5",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "15",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "5"
  },
  {
      "router_customer_brand_id": "92",
      "companyName": "GoldenHighHeels",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "30",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "5",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "30"
  },
  {
      "router_customer_brand_id": "166",
      "companyName": "Greenglide",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "282",
      "companyName": "Hachille",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "3",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "261",
      "companyName": "Healthential",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "215",
      "companyName": "Highbridge Trading",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "96",
      "companyName": "HIPHBIO",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "113",
      "companyName": "HODBV",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "279",
      "companyName": "iJi.éco",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "236",
      "companyName": "INBS",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "149",
      "companyName": "INOVELTEC",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "184",
      "companyName": "INREDI",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "136",
      "companyName": "It's Time Limited",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "168",
      "companyName": "IWI AND CO",
      "logo": "logo_iwiandco.png",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "145",
      "companyName": "jmc billard",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "250",
      "companyName": "JMD",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "830",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "169",
      "companyName": "Joozia",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "2",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "3",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "2"
  },
  {
      "router_customer_brand_id": "265",
      "companyName": "Jovencia",
      "logo": "",
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "38",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "38"
  },
  {
      "router_customer_brand_id": "239",
      "companyName": "Kilogrammes",
      "logo": null,
      "nbnew": "4",
      "idnew": "1",
      "nbprint": "113",
      "idprint": "4",
      "nbblocked": "41",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "113"
  },
  {
      "router_customer_brand_id": "158",
      "companyName": "Kitozyme",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "217",
      "companyName": "La Ferme du CBD",
      "logo": null,
      "nbnew": "596",
      "idnew": "1",
      "nbprint": "44",
      "idprint": "4",
      "nbblocked": "30",
      "idblocked": "3",
      "nbout_of_stock": "42",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "44"
  },
  {
      "router_customer_brand_id": "146",
      "companyName": "La Maison du Cap",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "174",
      "companyName": "Laboratoire Mergens",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "210",
      "companyName": "Laboratoires Bimont",
      "logo": null,
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "46",
      "idprint": "4",
      "nbblocked": "9",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "46"
  },
  {
      "router_customer_brand_id": "259",
      "companyName": "Lamerenda",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "2",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "2"
  },
  {
      "router_customer_brand_id": "230",
      "companyName": "Laola store",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "283",
      "companyName": "LB Corporate",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "263",
      "companyName": "LIFESPAN-PLUS",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "148",
      "companyName": "Little Storage",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "260",
      "companyName": "LivLabs",
      "logo": null,
      "nbnew": "2",
      "idnew": "1",
      "nbprint": "54",
      "idprint": "4",
      "nbblocked": "36",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "54"
  },
  {
      "router_customer_brand_id": "183",
      "companyName": "Loen",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "47",
      "companyName": "Luxdiscount",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "125",
      "companyName": "Luxroutage",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "254",
      "companyName": "MAISON DES ENERVES",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "280",
      "companyName": "Meeliora",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "97",
      "companyName": "MERGENS SPORT LTD",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "268",
      "companyName": "MJZ INTERNATIONAL",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "2",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "275",
      "companyName": "Mobidistribution",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "134",
      "companyName": "mykronoz",
      "logo": "logo_mykronoz.png",
      "nbnew": "",
      "idnew": null,
      "nbprint": "11",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "7",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "11"
  },
  {
      "router_customer_brand_id": "90",
      "companyName": "nai",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "112",
      "companyName": "Natura4ever archive",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "108",
      "companyName": "Natural Labs",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "2",
      "idprint": "4",
      "nbblocked": "196",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "2"
  },
  {
      "router_customer_brand_id": "278",
      "companyName": "Nawaysupps",
      "logo": "",
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "3",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "3"
  },
  {
      "router_customer_brand_id": "196",
      "companyName": "Néo Nutrition",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "160",
      "companyName": "NEWCONCEPTS",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "167",
      "companyName": "NEWCONCEPTS FT",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "266",
      "companyName": "Nin-nin-game",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "74",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "74"
  },
  {
      "router_customer_brand_id": "109",
      "companyName": "Nippon-Yasan",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "262",
      "companyName": "Nootrawpics",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "267",
      "companyName": "Nordicdots",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "67",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "67"
  },
  {
      "router_customer_brand_id": "241",
      "companyName": "NORTHSTONE",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "231",
      "companyName": "Nouvelle Page",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "3",
      "idprint": "4",
      "nbblocked": "18",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "3"
  },
  {
      "router_customer_brand_id": "65",
      "companyName": "Nova Health Solution",
      "logo": "logo_novahealth.png",
      "nbnew": "2",
      "idnew": "1",
      "nbprint": "258",
      "idprint": "4",
      "nbblocked": "19",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "258"
  },
  {
      "router_customer_brand_id": "45",
      "companyName": "Novestige",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "52",
      "companyName": "Nutriform",
      "logo": null,
      "nbnew": "49",
      "idnew": "1",
      "nbprint": "35",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "35"
  },
  {
      "router_customer_brand_id": "43",
      "companyName": "Nutrilife",
      "logo": null,
      "nbnew": "78",
      "idnew": "1",
      "nbprint": "61",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "61"
  },
  {
      "router_customer_brand_id": "208",
      "companyName": "Nutrilife SARL",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "147",
      "companyName": "Ocsial",
      "logo": "logo_ocsial.png",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "114",
      "companyName": "OLIGOSCAN",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "138",
      "companyName": "Olliscience",
      "logo": "logo_olli.png",
      "nbnew": "",
      "idnew": null,
      "nbprint": "69",
      "idprint": "4",
      "nbblocked": "12",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "69"
  },
  {
      "router_customer_brand_id": "155",
      "companyName": "OTC Trade",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "23",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "23"
  },
  {
      "router_customer_brand_id": "177",
      "companyName": "Paatsh",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "140",
      "companyName": "Parabolic Biologicals",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "157",
      "companyName": "Perfect Skin",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "175",
      "companyName": "Perifit",
      "logo": "logo_perifit.png",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "61",
      "companyName": "PHS",
      "logo": null,
      "nbnew": "30",
      "idnew": "1",
      "nbprint": "78",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "78"
  },
  {
      "router_customer_brand_id": "235",
      "companyName": "PREMIER SERVICE",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "181",
      "companyName": "PROTIBIO",
      "logo": null,
      "nbnew": "3",
      "idnew": "1",
      "nbprint": "4",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "4"
  },
  {
      "router_customer_brand_id": "180",
      "companyName": "Psotherapy",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "232",
      "companyName": "PureSanté Nutrition",
      "logo": "",
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "99",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "99"
  },
  {
      "router_customer_brand_id": "221",
      "companyName": "RAPIDE2018",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "1",
      "companyName": "RCZ Bike Shop",
      "logo": "logo_rcz.jpg",
      "nbnew": "9",
      "idnew": "1",
      "nbprint": "44",
      "idprint": "4",
      "nbblocked": "42",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "44"
  },
  {
      "router_customer_brand_id": "237",
      "companyName": "Relaed",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "253",
      "companyName": "SAÏRAÏA SA",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "99",
      "companyName": "Santarel",
      "logo": null,
      "nbnew": "15",
      "idnew": "1",
      "nbprint": "37",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "37"
  },
  {
      "router_customer_brand_id": "137",
      "companyName": "Santi-shop",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "15",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "15"
  },
  {
      "router_customer_brand_id": "81",
      "companyName": "Senior autonome",
      "logo": null,
      "nbnew": "2",
      "idnew": "1",
      "nbprint": "16",
      "idprint": "4",
      "nbblocked": "216",
      "idblocked": "3",
      "nbout_of_stock": "9",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "16"
  },
  {
      "router_customer_brand_id": "214",
      "companyName": "ServicePrime",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "251",
      "companyName": "Shopigroup",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "269",
      "companyName": "SO VITAMIN",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "1",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "1"
  },
  {
      "router_customer_brand_id": "3",
      "companyName": "Sofinnov",
      "logo": "sofilogo.jpg",
      "nbnew": "10",
      "idnew": "1",
      "nbprint": "88",
      "idprint": "4",
      "nbblocked": "3",
      "idblocked": "3",
      "nbout_of_stock": "66",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "88"
  },
  {
      "router_customer_brand_id": "252",
      "companyName": "Stone Age",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "16",
      "idblocked": "3",
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "256",
      "companyName": "Therabelgique",
      "logo": null,
      "nbnew": "4",
      "idnew": "1",
      "nbprint": "43",
      "idprint": "4",
      "nbblocked": "24",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "43"
  },
  {
      "router_customer_brand_id": "245",
      "companyName": "Theralux",
      "logo": null,
      "nbnew": "2",
      "idnew": "1",
      "nbprint": "2",
      "idprint": "4",
      "nbblocked": "12",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "2"
  },
  {
      "router_customer_brand_id": "187",
      "companyName": "TOTAL SANTE",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "27",
      "idprint": "4",
      "nbblocked": "6",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "27"
  },
  {
      "router_customer_brand_id": "212",
      "companyName": "UNBT",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "63",
      "companyName": "VIAPHYT",
      "logo": null,
      "nbnew": "4",
      "idnew": "1",
      "nbprint": "2",
      "idprint": "4",
      "nbblocked": "23",
      "idblocked": "3",
      "nbout_of_stock": "2",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "2"
  },
  {
      "router_customer_brand_id": "205",
      "companyName": "Vienergie",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "120",
      "companyName": "VITACELLSCREEN",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "4",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "4"
  },
  {
      "router_customer_brand_id": "222",
      "companyName": "Vitalbio",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "67",
      "companyName": "Vitamin Express",
      "logo": null,
      "nbnew": "183",
      "idnew": "1",
      "nbprint": "888",
      "idprint": "4",
      "nbblocked": "1",
      "idblocked": "3",
      "nbout_of_stock": "5",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "888"
  },
  {
      "router_customer_brand_id": "84",
      "companyName": "vitasunn",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "62",
      "idprint": "4",
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "62"
  },
  {
      "router_customer_brand_id": "281",
      "companyName": "Wasch",
      "logo": "",
      "nbnew": "1",
      "idnew": "1",
      "nbprint": "",
      "idprint": null,
      "nbblocked": "26",
      "idblocked": "3",
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "255",
      "companyName": "Weedy",
      "logo": "",
      "nbnew": "14",
      "idnew": "1",
      "nbprint": "226",
      "idprint": "4",
      "nbblocked": "69",
      "idblocked": "3",
      "nbout_of_stock": "1",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "226"
  },
  {
      "router_customer_brand_id": "246",
      "companyName": "Woodskine",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "226",
      "companyName": "WoreyD.",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "186",
      "companyName": "Xelliss",
      "logo": null,
      "nbnew": "337",
      "idnew": "1",
      "nbprint": "124",
      "idprint": "4",
      "nbblocked": "9",
      "idblocked": "3",
      "nbout_of_stock": "57",
      "idoutofstock": "7",
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": "124"
  },
  {
      "router_customer_brand_id": "59",
      "companyName": "xsslim",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "204",
      "companyName": "ybela",
      "logo": "",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "248",
      "companyName": "Yourhealthyfix",
      "logo": null,
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  },
  {
      "router_customer_brand_id": "68",
      "companyName": "Zabok",
      "logo": "logo_za.jpg",
      "nbnew": "",
      "idnew": null,
      "nbprint": "",
      "idprint": null,
      "nbblocked": "",
      "idblocked": null,
      "nbout_of_stock": "",
      "idoutofstock": null,
      "nbpreparedday": "",
      "idpreparedday": null,
      "nb_printyesterday": ""
  }
];


const Dashboard: React.FC = () => {

  const token:string = sessionStorage.getItem('api_token')+''; 
  const [data,setData] = useState([]);

  useEffect( ()=>{
    
   // loadData(data);
    console.log('use ffect')

} , [])

  
const loadData = async (getdate:any) => {
  
  var link = 'http://127.0.0.1:8000/api/dashboard';

  await fetch(link, {
     method: "GET",
     headers: {"Content-type": "application/json;charset=UTF-8" , 'x-api-token' : token}
     })
     .then(response => response.json())
     .then(recievedData => setData(recievedData));
}

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar color="warning">
          <IonTitle>Dashboard</IonTitle>
          <IonButtons slot="end">
            <NavButtons/>
          </IonButtons>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>

      <br />
      <IonHeader>TODAY'S DASHBOARD</IonHeader>
      <br /><br />

      { dash == null || dash == [] || dash.length == 0  ? <IonLoading isOpen={true} ></IonLoading> : console.log('toto',dash)}
      { /* data == null || data == [] || data.length == 0  ? <IonLoading isOpen={true} message={"Waiting for data..."}></IonLoading> : <LRItableCollectionBody data={data} /> */}

      <TableWrapper title="ok">
      <LRITableHeaders cols={dash[0]} />
      <LRItableCollectionBody data={dash} />
      </TableWrapper>
      </IonContent>
    </IonPage>

   
  );
};

export default Dashboard;
